server: 
  port: 8770
spring: 
  application:  
    name: service-config
  cloud:	
  	config:	
  		server:	
  			git:	
  				uri:	https://github.com/136759790/
eureka: 
  client: 
    serviceUrl: 
      defaultZone:  http://localhost:8761/eureka/