server: 
  port: 8764
spring: 
  application:  
    name: service-ribbon
  zipkin: 
    base-url: http://localhost:8775
eureka: 
  client: 
    serviceUrl: 
      defaultZone:  http://localhost:8761/eureka/